/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomStatus } from './RoomStatus';
import { RoomStatusFromJSON, RoomStatusFromJSONTyped, RoomStatusToJSON } from './RoomStatus';

/**
 *
 * @export
 * @interface AttractionAdminServiceUpdateStatusBody
 */
export interface AttractionAdminServiceUpdateStatusBody {
  /**
   *
   * @type {RoomStatus}
   * @memberof AttractionAdminServiceUpdateStatusBody
   */
  status?: RoomStatus;
}

/**
 * Check if a given object implements the AttractionAdminServiceUpdateStatusBody interface.
 */
export function instanceOfAttractionAdminServiceUpdateStatusBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AttractionAdminServiceUpdateStatusBodyFromJSON(
  json: any,
): AttractionAdminServiceUpdateStatusBody {
  return AttractionAdminServiceUpdateStatusBodyFromJSONTyped(json, false);
}

export function AttractionAdminServiceUpdateStatusBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AttractionAdminServiceUpdateStatusBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, 'status') ? undefined : RoomStatusFromJSON(json['status']),
  };
}

export function AttractionAdminServiceUpdateStatusBodyToJSON(
  value?: AttractionAdminServiceUpdateStatusBody | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: RoomStatusToJSON(value.status),
  };
}
