/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Attraction } from './Attraction';
import { AttractionFromJSON, AttractionFromJSONTyped, AttractionToJSON } from './Attraction';

/**
 *
 * @export
 * @interface AttractionCreateReq
 */
export interface AttractionCreateReq {
  /**
   *
   * @type {Attraction}
   * @memberof AttractionCreateReq
   */
  attraction: Attraction;
}

/**
 * Check if a given object implements the AttractionCreateReq interface.
 */
export function instanceOfAttractionCreateReq(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'attraction' in value;

  return isInstance;
}

export function AttractionCreateReqFromJSON(json: any): AttractionCreateReq {
  return AttractionCreateReqFromJSONTyped(json, false);
}

export function AttractionCreateReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AttractionCreateReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    attraction: AttractionFromJSON(json['attraction']),
  };
}

export function AttractionCreateReqToJSON(value?: AttractionCreateReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    attraction: AttractionToJSON(value.attraction),
  };
}
