/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthVerifyResponse
 */
export interface AuthVerifyResponse {
  /**
   *
   * @type {boolean}
   * @memberof AuthVerifyResponse
   */
  ok: boolean;
  /**
   *
   * @type {string}
   * @memberof AuthVerifyResponse
   */
  claims: string;
}

/**
 * Check if a given object implements the AuthVerifyResponse interface.
 */
export function instanceOfAuthVerifyResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'ok' in value;
  isInstance = isInstance && 'claims' in value;

  return isInstance;
}

export function AuthVerifyResponseFromJSON(json: any): AuthVerifyResponse {
  return AuthVerifyResponseFromJSONTyped(json, false);
}

export function AuthVerifyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthVerifyResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ok: json['ok'],
    claims: json['claims'],
  };
}

export function AuthVerifyResponseToJSON(value?: AuthVerifyResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ok: value.ok,
    claims: value.claims,
  };
}
