/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthRefreshResponse
 */
export interface AuthRefreshResponse {
  /**
   *
   * @type {string}
   * @memberof AuthRefreshResponse
   */
  jwtToken: string;
}

/**
 * Check if a given object implements the AuthRefreshResponse interface.
 */
export function instanceOfAuthRefreshResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'jwtToken' in value;

  return isInstance;
}

export function AuthRefreshResponseFromJSON(json: any): AuthRefreshResponse {
  return AuthRefreshResponseFromJSONTyped(json, false);
}

export function AuthRefreshResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthRefreshResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    jwtToken: json['jwtToken'],
  };
}

export function AuthRefreshResponseToJSON(value?: AuthRefreshResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    jwtToken: value.jwtToken,
  };
}
