/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthAuthorizeRsp
 */
export interface AuthAuthorizeRsp {
  /**
   *
   * @type {string}
   * @memberof AuthAuthorizeRsp
   */
  redirectUri: string;
}

/**
 * Check if a given object implements the AuthAuthorizeRsp interface.
 */
export function instanceOfAuthAuthorizeRsp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'redirectUri' in value;

  return isInstance;
}

export function AuthAuthorizeRspFromJSON(json: any): AuthAuthorizeRsp {
  return AuthAuthorizeRspFromJSONTyped(json, false);
}

export function AuthAuthorizeRspFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthAuthorizeRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    redirectUri: json['redirectUri'],
  };
}

export function AuthAuthorizeRspToJSON(value?: AuthAuthorizeRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    redirectUri: value.redirectUri,
  };
}
