/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthRefreshRequest
 */
export interface AuthRefreshRequest {
  /**
   *
   * @type {string}
   * @memberof AuthRefreshRequest
   */
  token: string;
}

/**
 * Check if a given object implements the AuthRefreshRequest interface.
 */
export function instanceOfAuthRefreshRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'token' in value;

  return isInstance;
}

export function AuthRefreshRequestFromJSON(json: any): AuthRefreshRequest {
  return AuthRefreshRequestFromJSONTyped(json, false);
}

export function AuthRefreshRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthRefreshRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    token: json['token'],
  };
}

export function AuthRefreshRequestToJSON(value?: AuthRefreshRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    token: value.token,
  };
}
