/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BannerType = {
  Home: 'type_home',
  Order: 'type_order',
  StoreInfo: 'type_store_info',
  PointsInfo: 'type_points_info',
} as const;
export type BannerType = (typeof BannerType)[keyof typeof BannerType];

export function BannerTypeFromJSON(json: any): BannerType {
  return BannerTypeFromJSONTyped(json, false);
}

export function BannerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BannerType {
  return json as BannerType;
}

export function BannerTypeToJSON(value?: BannerType | null): any {
  return value as any;
}
