/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Banner } from './Banner';
import { BannerFromJSON, BannerFromJSONTyped, BannerToJSON } from './Banner';

/**
 *
 * @export
 * @interface Banners
 */
export interface Banners {
  /**
   *
   * @type {Array<Banner>}
   * @memberof Banners
   */
  data?: Array<Banner>;
}

/**
 * Check if a given object implements the Banners interface.
 */
export function instanceOfBanners(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function BannersFromJSON(json: any): Banners {
  return BannersFromJSONTyped(json, false);
}

export function BannersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Banners {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(BannerFromJSON),
  };
}

export function BannersToJSON(value?: Banners | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(BannerToJSON),
  };
}
