/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BindAndVerifyBody
 */
export interface BindAndVerifyBody {
  /**
   *
   * @type {string}
   * @memberof BindAndVerifyBody
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof BindAndVerifyBody
   */
  signature?: string;
  /**
   *
   * @type {string}
   * @memberof BindAndVerifyBody
   */
  nonce?: string;
}

/**
 * Check if a given object implements the BindAndVerifyBody interface.
 */
export function instanceOfBindAndVerifyBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function BindAndVerifyBodyFromJSON(json: any): BindAndVerifyBody {
  return BindAndVerifyBodyFromJSONTyped(json, false);
}

export function BindAndVerifyBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BindAndVerifyBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    signature: !exists(json, 'signature') ? undefined : json['signature'],
    nonce: !exists(json, 'nonce') ? undefined : json['nonce'],
  };
}

export function BindAndVerifyBodyToJSON(value?: BindAndVerifyBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    signature: value.signature,
    nonce: value.nonce,
  };
}
