/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CancellationPolicy = {
  Easy: 'policy_easy',
  Normal: 'policy_normal',
  Strict: 'policy_strict',
} as const;
export type CancellationPolicy = (typeof CancellationPolicy)[keyof typeof CancellationPolicy];

export function CancellationPolicyFromJSON(json: any): CancellationPolicy {
  return CancellationPolicyFromJSONTyped(json, false);
}

export function CancellationPolicyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancellationPolicy {
  return json as CancellationPolicy;
}

export function CancellationPolicyToJSON(value?: CancellationPolicy | null): any {
  return value as any;
}
