/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CheckRoomBookableRsp
 */
export interface CheckRoomBookableRsp {
  /**
   *
   * @type {boolean}
   * @memberof CheckRoomBookableRsp
   */
  bookable?: boolean;
}

/**
 * Check if a given object implements the CheckRoomBookableRsp interface.
 */
export function instanceOfCheckRoomBookableRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CheckRoomBookableRspFromJSON(json: any): CheckRoomBookableRsp {
  return CheckRoomBookableRspFromJSONTyped(json, false);
}

export function CheckRoomBookableRspFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckRoomBookableRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    bookable: !exists(json, 'bookable') ? undefined : json['bookable'],
  };
}

export function CheckRoomBookableRspToJSON(value?: CheckRoomBookableRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    bookable: value.bookable,
  };
}
