/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CouponLevel = {
  _0: 'level_0',
  _1: 'level_1',
  _2: 'level_2',
  _3: 'level_3',
  _4: 'level_4',
  _5: 'level_5',
  _6: 'level_6',
  _7: 'level_7',
  _8: 'level_8',
  _9: 'level_9',
} as const;
export type CouponLevel = (typeof CouponLevel)[keyof typeof CouponLevel];

export function CouponLevelFromJSON(json: any): CouponLevel {
  return CouponLevelFromJSONTyped(json, false);
}

export function CouponLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponLevel {
  return json as CouponLevel;
}

export function CouponLevelToJSON(value?: CouponLevel | null): any {
  return value as any;
}
