/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coupon } from './Coupon';
import { CouponFromJSON, CouponFromJSONTyped, CouponToJSON } from './Coupon';

/**
 *
 * @export
 * @interface Coupons
 */
export interface Coupons {
  /**
   *
   * @type {Array<Coupon>}
   * @memberof Coupons
   */
  data?: Array<Coupon>;
  /**
   *
   * @type {number}
   * @memberof Coupons
   */
  total?: number;
}

/**
 * Check if a given object implements the Coupons interface.
 */
export function instanceOfCoupons(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CouponsFromJSON(json: any): Coupons {
  return CouponsFromJSONTyped(json, false);
}

export function CouponsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Coupons {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(CouponFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function CouponsToJSON(value?: Coupons | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(CouponToJSON),
    total: value.total,
  };
}
