/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CouponKind = {
  SysCoupon: 'sys_coupon',
  RoomShare: 'room_share',
  NftRebate: 'nft_rebate',
  UserInvite: 'user_invite',
  RoomCheckIn: 'room_check_in',
  Reward: 'reward',
  OrderComment: 'order_comment',
  UserUsed: 'user_used',
  UserRegister: 'user_register',
  FinishUserInfo: 'finish_user_info',
  SysAdminOperate: 'sys_admin_operate',
  StoreRegister: 'store_register',
  UserExchange: 'user_exchange',
  LuckyDrawPoints: 'lucky_draw_points',
  LuckyDrawConsume: 'lucky_draw_consume',
} as const;
export type CouponKind = (typeof CouponKind)[keyof typeof CouponKind];

export function CouponKindFromJSON(json: any): CouponKind {
  return CouponKindFromJSONTyped(json, false);
}

export function CouponKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponKind {
  return json as CouponKind;
}

export function CouponKindToJSON(value?: CouponKind | null): any {
  return value as any;
}
