/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * - ACTIVATE: 激活
 *  - FREEZE: 冻结
 * @export
 */
export const CouponAdjustPointsReqType = {
  Unrecognized: 'UNRECOGNIZED',
  Activate: 'ACTIVATE',
  Freeze: 'FREEZE',
} as const;
export type CouponAdjustPointsReqType =
  (typeof CouponAdjustPointsReqType)[keyof typeof CouponAdjustPointsReqType];

export function CouponAdjustPointsReqTypeFromJSON(json: any): CouponAdjustPointsReqType {
  return CouponAdjustPointsReqTypeFromJSONTyped(json, false);
}

export function CouponAdjustPointsReqTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CouponAdjustPointsReqType {
  return json as CouponAdjustPointsReqType;
}

export function CouponAdjustPointsReqTypeToJSON(value?: CouponAdjustPointsReqType | null): any {
  return value as any;
}
