/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateExchangeRecordReq
 */
export interface CreateExchangeRecordReq {
  /**
   *
   * @type {string}
   * @memberof CreateExchangeRecordReq
   */
  goodId?: string;
  /**
   *
   * @type {string}
   * @memberof CreateExchangeRecordReq
   */
  userAddressId?: string;
}

/**
 * Check if a given object implements the CreateExchangeRecordReq interface.
 */
export function instanceOfCreateExchangeRecordReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreateExchangeRecordReqFromJSON(json: any): CreateExchangeRecordReq {
  return CreateExchangeRecordReqFromJSONTyped(json, false);
}

export function CreateExchangeRecordReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateExchangeRecordReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    goodId: !exists(json, 'goodId') ? undefined : json['goodId'],
    userAddressId: !exists(json, 'userAddressId') ? undefined : json['userAddressId'],
  };
}

export function CreateExchangeRecordReqToJSON(value?: CreateExchangeRecordReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    goodId: value.goodId,
    userAddressId: value.userAddressId,
  };
}
