/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorsErrCode } from './ErrorsErrCode';
import {
  ErrorsErrCodeFromJSON,
  ErrorsErrCodeFromJSONTyped,
  ErrorsErrCodeToJSON,
} from './ErrorsErrCode';
import type { V1Code } from './V1Code';
import { V1CodeFromJSON, V1CodeFromJSONTyped, V1CodeToJSON } from './V1Code';

/**
 *
 * @export
 * @interface ErrCodeRsp
 */
export interface ErrCodeRsp {
  /**
   *
   * @type {Array<ErrorsErrCode>}
   * @memberof ErrCodeRsp
   */
  codes?: Array<ErrorsErrCode>;
  /**
   *
   * @type {V1Code}
   * @memberof ErrCodeRsp
   */
  code?: V1Code;
}

/**
 * Check if a given object implements the ErrCodeRsp interface.
 */
export function instanceOfErrCodeRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ErrCodeRspFromJSON(json: any): ErrCodeRsp {
  return ErrCodeRspFromJSONTyped(json, false);
}

export function ErrCodeRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrCodeRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    codes: !exists(json, 'codes')
      ? undefined
      : (json['codes'] as Array<any>).map(ErrorsErrCodeFromJSON),
    code: !exists(json, 'code') ? undefined : V1CodeFromJSON(json['code']),
  };
}

export function ErrCodeRspToJSON(value?: ErrCodeRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    codes:
      value.codes === undefined ? undefined : (value.codes as Array<any>).map(ErrorsErrCodeToJSON),
    code: V1CodeToJSON(value.code),
  };
}
