/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetRoomOrderPriceRsp
 */
export interface GetRoomOrderPriceRsp {
  /**
   *
   * @type {number}
   * @memberof GetRoomOrderPriceRsp
   */
  days?: number | null;
  /**
   *
   * @type {string}
   * @memberof GetRoomOrderPriceRsp
   */
  totalPrice?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof GetRoomOrderPriceRsp
   */
  bookable?: boolean | null;
  /**
   *
   * @type {object}
   * @memberof GetRoomOrderPriceRsp
   */
  detail?: object | null;
}

/**
 * Check if a given object implements the GetRoomOrderPriceRsp interface.
 */
export function instanceOfGetRoomOrderPriceRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetRoomOrderPriceRspFromJSON(json: any): GetRoomOrderPriceRsp {
  return GetRoomOrderPriceRspFromJSONTyped(json, false);
}

export function GetRoomOrderPriceRspFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetRoomOrderPriceRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    days: !exists(json, 'days') ? undefined : json['days'],
    totalPrice: !exists(json, 'totalPrice') ? undefined : json['totalPrice'],
    bookable: !exists(json, 'bookable') ? undefined : json['bookable'],
    detail: !exists(json, 'detail') ? undefined : json['detail'],
  };
}

export function GetRoomOrderPriceRspToJSON(value?: GetRoomOrderPriceRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    days: value.days,
    totalPrice: value.totalPrice,
    bookable: value.bookable,
    detail: value.detail,
  };
}
