/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IdReq
 */
export interface IdReq {
  /**
   *
   * @type {string}
   * @memberof IdReq
   */
  id?: string;
}

/**
 * Check if a given object implements the IdReq interface.
 */
export function instanceOfIdReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IdReqFromJSON(json: any): IdReq {
  return IdReqFromJSONTyped(json, false);
}

export function IdReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function IdReqToJSON(value?: IdReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
