/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Inner
 */
export interface Inner {
  /**
   *
   * @type {number}
   * @memberof Inner
   */
  commentCount?: number;
  /**
   *
   * @type {number}
   * @memberof Inner
   */
  commentRating?: number;
}

/**
 * Check if a given object implements the Inner interface.
 */
export function instanceOfInner(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function InnerFromJSON(json: any): Inner {
  return InnerFromJSONTyped(json, false);
}

export function InnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Inner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    commentCount: !exists(json, 'commentCount') ? undefined : json['commentCount'],
    commentRating: !exists(json, 'commentRating') ? undefined : json['commentRating'],
  };
}

export function InnerToJSON(value?: Inner | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    commentCount: value.commentCount,
    commentRating: value.commentRating,
  };
}
