/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const KindType = {
  Airbnb: 'airbnb',
} as const;
export type KindType = (typeof KindType)[keyof typeof KindType];

export function KindTypeFromJSON(json: any): KindType {
  return KindTypeFromJSONTyped(json, false);
}

export function KindTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KindType {
  return json as KindType;
}

export function KindTypeToJSON(value?: KindType | null): any {
  return value as any;
}
