/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Message
 */
export interface Message {
  /**
   *
   * @type {string}
   * @memberof Message
   */
  messageId?: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  userId?: string;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function MessageFromJSON(json: any): Message {
  return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    messageId: !exists(json, 'messageId') ? undefined : json['messageId'],
    text: !exists(json, 'text') ? undefined : json['text'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
  };
}

export function MessageToJSON(value?: Message | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    messageId: value.messageId,
    text: value.text,
    userId: value.userId,
  };
}
