/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SpecialOrder } from './SpecialOrder';
import {
  SpecialOrderFromJSON,
  SpecialOrderFromJSONTyped,
  SpecialOrderToJSON,
} from './SpecialOrder';

/**
 *
 * @export
 * @interface OrderSpecialCreateReq
 */
export interface OrderSpecialCreateReq {
  /**
   *
   * @type {Array<SpecialOrder>}
   * @memberof OrderSpecialCreateReq
   */
  order?: Array<SpecialOrder>;
}

/**
 * Check if a given object implements the OrderSpecialCreateReq interface.
 */
export function instanceOfOrderSpecialCreateReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderSpecialCreateReqFromJSON(json: any): OrderSpecialCreateReq {
  return OrderSpecialCreateReqFromJSONTyped(json, false);
}

export function OrderSpecialCreateReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderSpecialCreateReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    order: !exists(json, 'order')
      ? undefined
      : (json['order'] as Array<any>).map(SpecialOrderFromJSON),
  };
}

export function OrderSpecialCreateReqToJSON(value?: OrderSpecialCreateReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    order:
      value.order === undefined ? undefined : (value.order as Array<any>).map(SpecialOrderToJSON),
  };
}
