/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Order } from './Order';
import { OrderFromJSON, OrderFromJSONTyped, OrderToJSON } from './Order';

/**
 *
 * @export
 * @interface Orders
 */
export interface Orders {
  /**
   *
   * @type {Array<Order>}
   * @memberof Orders
   */
  orders?: Array<Order>;
  /**
   *
   * @type {number}
   * @memberof Orders
   */
  total?: number;
}

/**
 * Check if a given object implements the Orders interface.
 */
export function instanceOfOrders(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrdersFromJSON(json: any): Orders {
  return OrdersFromJSONTyped(json, false);
}

export function OrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Orders {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orders: !exists(json, 'orders') ? undefined : (json['orders'] as Array<any>).map(OrderFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function OrdersToJSON(value?: Orders | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orders: value.orders === undefined ? undefined : (value.orders as Array<any>).map(OrderToJSON),
    total: value.total,
  };
}
