/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderSpecialCancelBody
 */
export interface OrderSpecialCancelBody {
  /**
   *
   * @type {string}
   * @memberof OrderSpecialCancelBody
   */
  reason?: string | null;
}

/**
 * Check if a given object implements the OrderSpecialCancelBody interface.
 */
export function instanceOfOrderSpecialCancelBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderSpecialCancelBodyFromJSON(json: any): OrderSpecialCancelBody {
  return OrderSpecialCancelBodyFromJSONTyped(json, false);
}

export function OrderSpecialCancelBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderSpecialCancelBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reason: !exists(json, 'reason') ? undefined : json['reason'],
  };
}

export function OrderSpecialCancelBodyToJSON(value?: OrderSpecialCancelBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reason: value.reason,
  };
}
