/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderPayType } from './OrderPayType';
import {
  OrderPayTypeFromJSON,
  OrderPayTypeFromJSONTyped,
  OrderPayTypeToJSON,
} from './OrderPayType';

/**
 *
 * @export
 * @interface OrderSpecialPayReq
 */
export interface OrderSpecialPayReq {
  /**
   *
   * @type {Array<string>}
   * @memberof OrderSpecialPayReq
   */
  id?: Array<string>;
  /**
   *
   * @type {OrderPayType}
   * @memberof OrderSpecialPayReq
   */
  type?: OrderPayType;
  /**
   *
   * @type {string}
   * @memberof OrderSpecialPayReq
   */
  currency?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderSpecialPayReq
   */
  network?: string | null;
}

/**
 * Check if a given object implements the OrderSpecialPayReq interface.
 */
export function instanceOfOrderSpecialPayReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderSpecialPayReqFromJSON(json: any): OrderSpecialPayReq {
  return OrderSpecialPayReqFromJSONTyped(json, false);
}

export function OrderSpecialPayReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderSpecialPayReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    type: !exists(json, 'type') ? undefined : OrderPayTypeFromJSON(json['type']),
    currency: !exists(json, 'currency') ? undefined : json['currency'],
    network: !exists(json, 'network') ? undefined : json['network'],
  };
}

export function OrderSpecialPayReqToJSON(value?: OrderSpecialPayReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    type: OrderPayTypeToJSON(value.type),
    currency: value.currency,
    network: value.network,
  };
}
