/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderGenOrderSpecialDetailReq
 */
export interface OrderGenOrderSpecialDetailReq {
  /**
   *
   * @type {string}
   * @memberof OrderGenOrderSpecialDetailReq
   */
  roomOrderId?: string;
  /**
   *
   * @type {string}
   * @memberof OrderGenOrderSpecialDetailReq
   */
  specialServiceId?: string;
  /**
   *
   * @type {string}
   * @memberof OrderGenOrderSpecialDetailReq
   */
  userId?: string;
}

/**
 * Check if a given object implements the OrderGenOrderSpecialDetailReq interface.
 */
export function instanceOfOrderGenOrderSpecialDetailReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderGenOrderSpecialDetailReqFromJSON(json: any): OrderGenOrderSpecialDetailReq {
  return OrderGenOrderSpecialDetailReqFromJSONTyped(json, false);
}

export function OrderGenOrderSpecialDetailReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderGenOrderSpecialDetailReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    roomOrderId: !exists(json, 'roomOrderId') ? undefined : json['roomOrderId'],
    specialServiceId: !exists(json, 'specialServiceId') ? undefined : json['specialServiceId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
  };
}

export function OrderGenOrderSpecialDetailReqToJSON(
  value?: OrderGenOrderSpecialDetailReq | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    roomOrderId: value.roomOrderId,
    specialServiceId: value.specialServiceId,
    userId: value.userId,
  };
}
