/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderServiceCancelBody
 */
export interface OrderServiceCancelBody {
  /**
   *
   * @type {string}
   * @memberof OrderServiceCancelBody
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof OrderServiceCancelBody
   */
  reason?: string | null;
}

/**
 * Check if a given object implements the OrderServiceCancelBody interface.
 */
export function instanceOfOrderServiceCancelBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderServiceCancelBodyFromJSON(json: any): OrderServiceCancelBody {
  return OrderServiceCancelBodyFromJSONTyped(json, false);
}

export function OrderServiceCancelBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderServiceCancelBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    reason: !exists(json, 'reason') ? undefined : json['reason'],
  };
}

export function OrderServiceCancelBodyToJSON(value?: OrderServiceCancelBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId,
    reason: value.reason,
  };
}
