/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderMessage } from './OrderMessage';
import {
  OrderMessageFromJSON,
  OrderMessageFromJSONTyped,
  OrderMessageToJSON,
} from './OrderMessage';

/**
 *
 * @export
 * @interface OrderMessages
 */
export interface OrderMessages {
  /**
   *
   * @type {Array<OrderMessage>}
   * @memberof OrderMessages
   */
  messages?: Array<OrderMessage>;
  /**
   *
   * @type {number}
   * @memberof OrderMessages
   */
  total?: number;
}

/**
 * Check if a given object implements the OrderMessages interface.
 */
export function instanceOfOrderMessages(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderMessagesFromJSON(json: any): OrderMessages {
  return OrderMessagesFromJSONTyped(json, false);
}

export function OrderMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderMessages {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    messages: !exists(json, 'messages')
      ? undefined
      : (json['messages'] as Array<any>).map(OrderMessageFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function OrderMessagesToJSON(value?: OrderMessages | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    messages:
      value.messages === undefined
        ? undefined
        : (value.messages as Array<any>).map(OrderMessageToJSON),
    total: value.total,
  };
}
