/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderIDRsp
 */
export interface OrderIDRsp {
  /**
   *
   * @type {string}
   * @memberof OrderIDRsp
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof OrderIDRsp
   */
  payId?: string;
}

/**
 * Check if a given object implements the OrderIDRsp interface.
 */
export function instanceOfOrderIDRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderIDRspFromJSON(json: any): OrderIDRsp {
  return OrderIDRspFromJSONTyped(json, false);
}

export function OrderIDRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderIDRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    payId: !exists(json, 'payId') ? undefined : json['payId'],
  };
}

export function OrderIDRspToJSON(value?: OrderIDRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    payId: value.payId,
  };
}
