/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Order } from './Order';
import { OrderFromJSON, OrderFromJSONTyped, OrderToJSON } from './Order';

/**
 *
 * @export
 * @interface OrderCreateReq
 */
export interface OrderCreateReq {
  /**
   *
   * @type {Order}
   * @memberof OrderCreateReq
   */
  order?: Order;
}

/**
 * Check if a given object implements the OrderCreateReq interface.
 */
export function instanceOfOrderCreateReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderCreateReqFromJSON(json: any): OrderCreateReq {
  return OrderCreateReqFromJSONTyped(json, false);
}

export function OrderCreateReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderCreateReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    order: !exists(json, 'order') ? undefined : OrderFromJSON(json['order']),
  };
}

export function OrderCreateReqToJSON(value?: OrderCreateReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    order: OrderToJSON(value.order),
  };
}
