/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Paging
 */
export interface Paging {
  /**
   *
   * @type {number}
   * @memberof Paging
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof Paging
   */
  offset?: number;
}

/**
 * Check if a given object implements the Paging interface.
 */
export function instanceOfPaging(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PagingFromJSON(json: any): Paging {
  return PagingFromJSONTyped(json, false);
}

export function PagingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Paging {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    limit: !exists(json, 'limit') ? undefined : json['limit'],
    offset: !exists(json, 'offset') ? undefined : json['offset'],
  };
}

export function PagingToJSON(value?: Paging | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    limit: value.limit,
    offset: value.offset,
  };
}
