/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderPayType } from './OrderPayType';
import {
  OrderPayTypeFromJSON,
  OrderPayTypeFromJSONTyped,
  OrderPayTypeToJSON,
} from './OrderPayType';

/**
 *
 * @export
 * @interface PayInfo
 */
export interface PayInfo {
  /**
   *
   * @type {string}
   * @memberof PayInfo
   */
  sender?: string | null;
  /**
   *
   * @type {OrderPayType}
   * @memberof PayInfo
   */
  type?: OrderPayType;
  /**
   *
   * @type {string}
   * @memberof PayInfo
   */
  currency?: string | null;
  /**
   *
   * @type {string}
   * @memberof PayInfo
   */
  network?: string | null;
}

/**
 * Check if a given object implements the PayInfo interface.
 */
export function instanceOfPayInfo(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PayInfoFromJSON(json: any): PayInfo {
  return PayInfoFromJSONTyped(json, false);
}

export function PayInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sender: !exists(json, 'sender') ? undefined : json['sender'],
    type: !exists(json, 'type') ? undefined : OrderPayTypeFromJSON(json['type']),
    currency: !exists(json, 'currency') ? undefined : json['currency'],
    network: !exists(json, 'network') ? undefined : json['network'],
  };
}

export function PayInfoToJSON(value?: PayInfo | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sender: value.sender,
    type: OrderPayTypeToJSON(value.type),
    currency: value.currency,
    network: value.network,
  };
}
