/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RedeemRaffleGoodBody
 */
export interface RedeemRaffleGoodBody {
  /**
   * // 收件人
   *   optional string receiver_name = 10;
   *
   *   // 收件人电话
   *   optional string receiver_phone = 2;
   *
   *   // 收件人地址
   *   optional string receiver_address = 3;
   * @type {string}
   * @memberof RedeemRaffleGoodBody
   */
  userAddressId?: string;
}

/**
 * Check if a given object implements the RedeemRaffleGoodBody interface.
 */
export function instanceOfRedeemRaffleGoodBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RedeemRaffleGoodBodyFromJSON(json: any): RedeemRaffleGoodBody {
  return RedeemRaffleGoodBodyFromJSONTyped(json, false);
}

export function RedeemRaffleGoodBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RedeemRaffleGoodBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userAddressId: !exists(json, 'userAddressId') ? undefined : json['userAddressId'],
  };
}

export function RedeemRaffleGoodBodyToJSON(value?: RedeemRaffleGoodBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userAddressId: value.userAddressId,
  };
}
