/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Room } from './Room';
import { RoomFromJSON, RoomFromJSONTyped, RoomToJSON } from './Room';
import type { Story } from './Story';
import { StoryFromJSON, StoryFromJSONTyped, StoryToJSON } from './Story';

/**
 *
 * @export
 * @interface ResData
 */
export interface ResData {
  /**
   *
   * @type {Story}
   * @memberof ResData
   */
  story?: Story;
  /**
   *
   * @type {Room}
   * @memberof ResData
   */
  room?: Room;
}

/**
 * Check if a given object implements the ResData interface.
 */
export function instanceOfResData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ResDataFromJSON(json: any): ResData {
  return ResDataFromJSONTyped(json, false);
}

export function ResDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    story: !exists(json, 'story') ? undefined : StoryFromJSON(json['story']),
    room: !exists(json, 'room') ? undefined : RoomFromJSON(json['room']),
  };
}

export function ResDataToJSON(value?: ResData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    story: StoryToJSON(value.story),
    room: RoomToJSON(value.room),
  };
}
