/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResetPasswordReq
 */
export interface ResetPasswordReq {
  /**
   *
   * @type {string}
   * @memberof ResetPasswordReq
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof ResetPasswordReq
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof ResetPasswordReq
   */
  verifyCode: string;
  /**
   *
   * @type {boolean}
   * @memberof ResetPasswordReq
   */
  isEncrypted?: boolean;
}

/**
 * Check if a given object implements the ResetPasswordReq interface.
 */
export function instanceOfResetPasswordReq(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'password' in value;
  isInstance = isInstance && 'verifyCode' in value;

  return isInstance;
}

export function ResetPasswordReqFromJSON(json: any): ResetPasswordReq {
  return ResetPasswordReqFromJSONTyped(json, false);
}

export function ResetPasswordReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResetPasswordReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    verifyCode: json['verifyCode'],
    isEncrypted: !exists(json, 'isEncrypted') ? undefined : json['isEncrypted'],
  };
}

export function ResetPasswordReqToJSON(value?: ResetPasswordReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    verifyCode: value.verifyCode,
    isEncrypted: value.isEncrypted,
  };
}
