/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RoleName = {
  NormalUser: 'normal_user',
  Manager: 'manager',
  Admin: 'admin',
} as const;
export type RoleName = (typeof RoleName)[keyof typeof RoleName];

export function RoleNameFromJSON(json: any): RoleName {
  return RoleNameFromJSONTyped(json, false);
}

export function RoleNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleName {
  return json as RoleName;
}

export function RoleNameToJSON(value?: RoleName | null): any {
  return value as any;
}
