/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomPolicy } from './RoomPolicy';
import { RoomPolicyFromJSON, RoomPolicyFromJSONTyped, RoomPolicyToJSON } from './RoomPolicy';

/**
 *
 * @export
 * @interface RoomPolicies
 */
export interface RoomPolicies {
  /**
   *
   * @type {Array<RoomPolicy>}
   * @memberof RoomPolicies
   */
  policies?: Array<RoomPolicy>;
  /**
   *
   * @type {Array<RoomPolicy>}
   * @memberof RoomPolicies
   */
  orders?: Array<RoomPolicy>;
}

/**
 * Check if a given object implements the RoomPolicies interface.
 */
export function instanceOfRoomPolicies(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomPoliciesFromJSON(json: any): RoomPolicies {
  return RoomPoliciesFromJSONTyped(json, false);
}

export function RoomPoliciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomPolicies {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    policies: !exists(json, 'policies')
      ? undefined
      : (json['policies'] as Array<any>).map(RoomPolicyFromJSON),
    orders: !exists(json, 'orders')
      ? undefined
      : (json['orders'] as Array<any>).map(RoomPolicyFromJSON),
  };
}

export function RoomPoliciesToJSON(value?: RoomPolicies | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    policies:
      value.policies === undefined
        ? undefined
        : (value.policies as Array<any>).map(RoomPolicyToJSON),
    orders:
      value.orders === undefined ? undefined : (value.orders as Array<any>).map(RoomPolicyToJSON),
  };
}
