/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RoomFreeService
 */
export interface RoomFreeService {
  /**
   *
   * @type {boolean}
   * @memberof RoomFreeService
   */
  breakfast: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomFreeService
   */
  housekeeper: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomFreeService
   */
  securityService: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomFreeService
   */
  luggageStorage: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomFreeService
   */
  hygieneCleaning: boolean;
}

/**
 * Check if a given object implements the RoomFreeService interface.
 */
export function instanceOfRoomFreeService(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'breakfast' in value;
  isInstance = isInstance && 'housekeeper' in value;
  isInstance = isInstance && 'securityService' in value;
  isInstance = isInstance && 'luggageStorage' in value;
  isInstance = isInstance && 'hygieneCleaning' in value;

  return isInstance;
}

export function RoomFreeServiceFromJSON(json: any): RoomFreeService {
  return RoomFreeServiceFromJSONTyped(json, false);
}

export function RoomFreeServiceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomFreeService {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    breakfast: json['breakfast'],
    housekeeper: json['housekeeper'],
    securityService: json['securityService'],
    luggageStorage: json['luggageStorage'],
    hygieneCleaning: json['hygieneCleaning'],
  };
}

export function RoomFreeServiceToJSON(value?: RoomFreeService | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    breakfast: value.breakfast,
    housekeeper: value.housekeeper,
    securityService: value.securityService,
    luggageStorage: value.luggageStorage,
    hygieneCleaning: value.hygieneCleaning,
  };
}
