/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomComment } from './RoomComment';
import { RoomCommentFromJSON, RoomCommentFromJSONTyped, RoomCommentToJSON } from './RoomComment';

/**
 *
 * @export
 * @interface RoomComments
 */
export interface RoomComments {
  /**
   *
   * @type {Array<RoomComment>}
   * @memberof RoomComments
   */
  comments?: Array<RoomComment>;
  /**
   *
   * @type {number}
   * @memberof RoomComments
   */
  total?: number;
}

/**
 * Check if a given object implements the RoomComments interface.
 */
export function instanceOfRoomComments(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomCommentsFromJSON(json: any): RoomComments {
  return RoomCommentsFromJSONTyped(json, false);
}

export function RoomCommentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomComments {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    comments: !exists(json, 'comments')
      ? undefined
      : (json['comments'] as Array<any>).map(RoomCommentFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function RoomCommentsToJSON(value?: RoomComments | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    comments:
      value.comments === undefined
        ? undefined
        : (value.comments as Array<any>).map(RoomCommentToJSON),
    total: value.total,
  };
}
