/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SortOrder } from './SortOrder';
import { SortOrderFromJSON, SortOrderFromJSONTyped, SortOrderToJSON } from './SortOrder';

/**
 *
 * @export
 * @interface RoomFindReqOrderField
 */
export interface RoomFindReqOrderField {
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  updatedAt?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  name?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  country?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  city?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  language?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  isTopped?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  rating?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  status?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  commentCount?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  bookCount?: SortOrder;
  /**
   *
   * @type {SortOrder}
   * @memberof RoomFindReqOrderField
   */
  price?: SortOrder;
}

/**
 * Check if a given object implements the RoomFindReqOrderField interface.
 */
export function instanceOfRoomFindReqOrderField(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomFindReqOrderFieldFromJSON(json: any): RoomFindReqOrderField {
  return RoomFindReqOrderFieldFromJSONTyped(json, false);
}

export function RoomFindReqOrderFieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomFindReqOrderField {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    updatedAt: !exists(json, 'updatedAt') ? undefined : SortOrderFromJSON(json['updatedAt']),
    name: !exists(json, 'name') ? undefined : SortOrderFromJSON(json['name']),
    country: !exists(json, 'country') ? undefined : SortOrderFromJSON(json['country']),
    city: !exists(json, 'city') ? undefined : SortOrderFromJSON(json['city']),
    language: !exists(json, 'language') ? undefined : SortOrderFromJSON(json['language']),
    isTopped: !exists(json, 'isTopped') ? undefined : SortOrderFromJSON(json['isTopped']),
    rating: !exists(json, 'rating') ? undefined : SortOrderFromJSON(json['rating']),
    status: !exists(json, 'status') ? undefined : SortOrderFromJSON(json['status']),
    commentCount: !exists(json, 'commentCount')
      ? undefined
      : SortOrderFromJSON(json['commentCount']),
    bookCount: !exists(json, 'bookCount') ? undefined : SortOrderFromJSON(json['bookCount']),
    price: !exists(json, 'price') ? undefined : SortOrderFromJSON(json['price']),
  };
}

export function RoomFindReqOrderFieldToJSON(value?: RoomFindReqOrderField | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    updatedAt: SortOrderToJSON(value.updatedAt),
    name: SortOrderToJSON(value.name),
    country: SortOrderToJSON(value.country),
    city: SortOrderToJSON(value.city),
    language: SortOrderToJSON(value.language),
    isTopped: SortOrderToJSON(value.isTopped),
    rating: SortOrderToJSON(value.rating),
    status: SortOrderToJSON(value.status),
    commentCount: SortOrderToJSON(value.commentCount),
    bookCount: SortOrderToJSON(value.bookCount),
    price: SortOrderToJSON(value.price),
  };
}
