/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomPolicy } from './RoomPolicy';
import { RoomPolicyFromJSON, RoomPolicyFromJSONTyped, RoomPolicyToJSON } from './RoomPolicy';

/**
 *
 * @export
 * @interface RoomUpdateDatePriceBody
 */
export interface RoomUpdateDatePriceBody {
  /**
   *
   * @type {Array<RoomPolicy>}
   * @memberof RoomUpdateDatePriceBody
   */
  policies?: Array<RoomPolicy>;
}

/**
 * Check if a given object implements the RoomUpdateDatePriceBody interface.
 */
export function instanceOfRoomUpdateDatePriceBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomUpdateDatePriceBodyFromJSON(json: any): RoomUpdateDatePriceBody {
  return RoomUpdateDatePriceBodyFromJSONTyped(json, false);
}

export function RoomUpdateDatePriceBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomUpdateDatePriceBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    policies: !exists(json, 'policies')
      ? undefined
      : (json['policies'] as Array<any>).map(RoomPolicyFromJSON),
  };
}

export function RoomUpdateDatePriceBodyToJSON(value?: RoomUpdateDatePriceBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    policies:
      value.policies === undefined
        ? undefined
        : (value.policies as Array<any>).map(RoomPolicyToJSON),
  };
}
