/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RoomInfrastructure
 */
export interface RoomInfrastructure {
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  airConditioning: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  washingMachine: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  wirelessNetwork: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  coatHanger: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  television: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RoomInfrastructure
   */
  blackout: boolean;
}

/**
 * Check if a given object implements the RoomInfrastructure interface.
 */
export function instanceOfRoomInfrastructure(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'airConditioning' in value;
  isInstance = isInstance && 'washingMachine' in value;
  isInstance = isInstance && 'wirelessNetwork' in value;
  isInstance = isInstance && 'coatHanger' in value;
  isInstance = isInstance && 'television' in value;
  isInstance = isInstance && 'blackout' in value;

  return isInstance;
}

export function RoomInfrastructureFromJSON(json: any): RoomInfrastructure {
  return RoomInfrastructureFromJSONTyped(json, false);
}

export function RoomInfrastructureFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomInfrastructure {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    airConditioning: json['airConditioning'],
    washingMachine: json['washingMachine'],
    wirelessNetwork: json['wirelessNetwork'],
    coatHanger: json['coatHanger'],
    television: json['television'],
    blackout: json['blackout'],
  };
}

export function RoomInfrastructureToJSON(value?: RoomInfrastructure | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    airConditioning: value.airConditioning,
    washingMachine: value.washingMachine,
    wirelessNetwork: value.wirelessNetwork,
    coatHanger: value.coatHanger,
    television: value.television,
    blackout: value.blackout,
  };
}
