/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RoomFeatures
 */
export interface RoomFeatures {
  /**
   *
   * @type {boolean}
   * @memberof RoomFeatures
   */
  commentTotal?: boolean | null;
}

/**
 * Check if a given object implements the RoomFeatures interface.
 */
export function instanceOfRoomFeatures(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomFeaturesFromJSON(json: any): RoomFeatures {
  return RoomFeaturesFromJSONTyped(json, false);
}

export function RoomFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomFeatures {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    commentTotal: !exists(json, 'commentTotal') ? undefined : json['commentTotal'],
  };
}

export function RoomFeaturesToJSON(value?: RoomFeatures | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    commentTotal: value.commentTotal,
  };
}
