/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomCrawler } from './RoomCrawler';
import { RoomCrawlerFromJSON, RoomCrawlerFromJSONTyped, RoomCrawlerToJSON } from './RoomCrawler';

/**
 *
 * @export
 * @interface RoomCrawlers
 */
export interface RoomCrawlers {
  /**
   *
   * @type {Array<RoomCrawler>}
   * @memberof RoomCrawlers
   */
  data?: Array<RoomCrawler>;
  /**
   *
   * @type {number}
   * @memberof RoomCrawlers
   */
  total?: number;
}

/**
 * Check if a given object implements the RoomCrawlers interface.
 */
export function instanceOfRoomCrawlers(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomCrawlersFromJSON(json: any): RoomCrawlers {
  return RoomCrawlersFromJSONTyped(json, false);
}

export function RoomCrawlersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomCrawlers {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(RoomCrawlerFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function RoomCrawlersToJSON(value?: RoomCrawlers | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(RoomCrawlerToJSON),
    total: value.total,
  };
}
