/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RoomPolicy
 */
export interface RoomPolicy {
  /**
   *
   * @type {string}
   * @memberof RoomPolicy
   */
  year?: string;
  /**
   *
   * @type {string}
   * @memberof RoomPolicy
   */
  mouth?: string;
  /**
   *
   * @type {string}
   * @memberof RoomPolicy
   */
  day?: string;
  /**
   *
   * @type {string}
   * @memberof RoomPolicy
   */
  price?: string;
  /**
   *
   * @type {boolean}
   * @memberof RoomPolicy
   */
  disabled?: boolean | null;
  /**
   *
   * @type {string}
   * @memberof RoomPolicy
   */
  readonly id?: string | null;
}

/**
 * Check if a given object implements the RoomPolicy interface.
 */
export function instanceOfRoomPolicy(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomPolicyFromJSON(json: any): RoomPolicy {
  return RoomPolicyFromJSONTyped(json, false);
}

export function RoomPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomPolicy {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    year: !exists(json, 'year') ? undefined : json['year'],
    mouth: !exists(json, 'mouth') ? undefined : json['mouth'],
    day: !exists(json, 'day') ? undefined : json['day'],
    price: !exists(json, 'price') ? undefined : json['price'],
    disabled: !exists(json, 'disabled') ? undefined : json['disabled'],
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function RoomPolicyToJSON(value?: RoomPolicy | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    year: value.year,
    mouth: value.mouth,
    day: value.day,
    price: value.price,
    disabled: value.disabled,
  };
}
