/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoomInfra } from './RoomInfra';
import { RoomInfraFromJSON, RoomInfraFromJSONTyped, RoomInfraToJSON } from './RoomInfra';

/**
 *
 * @export
 * @interface RoomInfras
 */
export interface RoomInfras {
  /**
   *
   * @type {Array<RoomInfra>}
   * @memberof RoomInfras
   */
  data?: Array<RoomInfra>;
  /**
   *
   * @type {number}
   * @memberof RoomInfras
   */
  total?: number;
}

/**
 * Check if a given object implements the RoomInfras interface.
 */
export function instanceOfRoomInfras(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomInfrasFromJSON(json: any): RoomInfras {
  return RoomInfrasFromJSONTyped(json, false);
}

export function RoomInfrasFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomInfras {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(RoomInfraFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function RoomInfrasToJSON(value?: RoomInfras | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(RoomInfraToJSON),
    total: value.total,
  };
}
