/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RoomInfo
 */
export interface RoomInfo {
  /**
   *
   * @type {number}
   * @memberof RoomInfo
   */
  rooms: number;
  /**
   *
   * @type {number}
   * @memberof RoomInfo
   */
  beds: number;
  /**
   *
   * @type {number}
   * @memberof RoomInfo
   */
  capacity: number;
  /**
   *
   * @type {number}
   * @memberof RoomInfo
   */
  bathrooms: number;
}

/**
 * Check if a given object implements the RoomInfo interface.
 */
export function instanceOfRoomInfo(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'rooms' in value;
  isInstance = isInstance && 'beds' in value;
  isInstance = isInstance && 'capacity' in value;
  isInstance = isInstance && 'bathrooms' in value;

  return isInstance;
}

export function RoomInfoFromJSON(json: any): RoomInfo {
  return RoomInfoFromJSONTyped(json, false);
}

export function RoomInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    rooms: json['rooms'],
    beds: json['beds'],
    capacity: json['capacity'],
    bathrooms: json['bathrooms'],
  };
}

export function RoomInfoToJSON(value?: RoomInfo | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    rooms: value.rooms,
    beds: value.beds,
    capacity: value.capacity,
    bathrooms: value.bathrooms,
  };
}
