/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SaveBodyBanner } from './SaveBodyBanner';
import {
  SaveBodyBannerFromJSON,
  SaveBodyBannerFromJSONTyped,
  SaveBodyBannerToJSON,
} from './SaveBodyBanner';

/**
 *
 * @export
 * @interface SaveBody
 */
export interface SaveBody {
  /**
   *
   * @type {SaveBodyBanner}
   * @memberof SaveBody
   */
  banner?: SaveBodyBanner;
}

/**
 * Check if a given object implements the SaveBody interface.
 */
export function instanceOfSaveBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SaveBodyFromJSON(json: any): SaveBody {
  return SaveBodyFromJSONTyped(json, false);
}

export function SaveBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    banner: !exists(json, 'banner') ? undefined : SaveBodyBannerFromJSON(json['banner']),
  };
}

export function SaveBodyToJSON(value?: SaveBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    banner: SaveBodyBannerToJSON(value.banner),
  };
}
