/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Language } from './Language';
import { LanguageFromJSON, LanguageFromJSONTyped, LanguageToJSON } from './Language';

/**
 *
 * @export
 * @interface SaveBodyBanner
 */
export interface SaveBodyBanner {
  /**
   *
   * @type {string}
   * @memberof SaveBodyBanner
   */
  readonly id?: string;
  /**
   *
   * @type {Date}
   * @memberof SaveBodyBanner
   */
  readonly createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof SaveBodyBanner
   */
  readonly updatedAt?: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof SaveBodyBanner
   */
  images?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SaveBodyBanner
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof SaveBodyBanner
   */
  description?: string;
  /**
   *
   * @type {Language}
   * @memberof SaveBodyBanner
   */
  language?: Language;
  /**
   *
   * @type {object}
   * @memberof SaveBodyBanner
   */
  details?: object;
}

/**
 * Check if a given object implements the SaveBodyBanner interface.
 */
export function instanceOfSaveBodyBanner(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SaveBodyBannerFromJSON(json: any): SaveBodyBanner {
  return SaveBodyBannerFromJSONTyped(json, false);
}

export function SaveBodyBannerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SaveBodyBanner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    images: !exists(json, 'images') ? undefined : json['images'],
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    language: !exists(json, 'language') ? undefined : LanguageFromJSON(json['language']),
    details: !exists(json, 'details') ? undefined : json['details'],
  };
}

export function SaveBodyBannerToJSON(value?: SaveBodyBanner | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    images: value.images,
    title: value.title,
    description: value.description,
    language: LanguageToJSON(value.language),
    details: value.details,
  };
}
