/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Language } from './Language';
import { LanguageFromJSON, LanguageFromJSONTyped, LanguageToJSON } from './Language';

/**
 *
 * @export
 * @interface ServiceCopyReq
 */
export interface ServiceCopyReq {
  /**
   *
   * @type {Array<Language>}
   * @memberof ServiceCopyReq
   */
  language?: Array<Language>;
  /**
   *
   * @type {string}
   * @memberof ServiceCopyReq
   */
  serviceCatalogId?: string;
}

/**
 * Check if a given object implements the ServiceCopyReq interface.
 */
export function instanceOfServiceCopyReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ServiceCopyReqFromJSON(json: any): ServiceCopyReq {
  return ServiceCopyReqFromJSONTyped(json, false);
}

export function ServiceCopyReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ServiceCopyReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    language: !exists(json, 'language')
      ? undefined
      : (json['language'] as Array<any>).map(LanguageFromJSON),
    serviceCatalogId: !exists(json, 'serviceCatalogId') ? undefined : json['serviceCatalogId'],
  };
}

export function ServiceCopyReqToJSON(value?: ServiceCopyReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    language:
      value.language === undefined ? undefined : (value.language as Array<any>).map(LanguageToJSON),
    serviceCatalogId: value.serviceCatalogId,
  };
}
