/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Sharing } from './Sharing';
import { SharingFromJSON, SharingFromJSONTyped, SharingToJSON } from './Sharing';

/**
 *
 * @export
 * @interface SharingList
 */
export interface SharingList {
  /**
   *
   * @type {Array<Sharing>}
   * @memberof SharingList
   */
  shares?: Array<Sharing>;
  /**
   *
   * @type {number}
   * @memberof SharingList
   */
  total?: number;
}

/**
 * Check if a given object implements the SharingList interface.
 */
export function instanceOfSharingList(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SharingListFromJSON(json: any): SharingList {
  return SharingListFromJSONTyped(json, false);
}

export function SharingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharingList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    shares: !exists(json, 'shares')
      ? undefined
      : (json['shares'] as Array<any>).map(SharingFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function SharingListToJSON(value?: SharingList | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    shares:
      value.shares === undefined ? undefined : (value.shares as Array<any>).map(SharingToJSON),
    total: value.total,
  };
}
