/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SpecialServiceCatalog } from './SpecialServiceCatalog';
import {
  SpecialServiceCatalogFromJSON,
  SpecialServiceCatalogFromJSONTyped,
  SpecialServiceCatalogToJSON,
} from './SpecialServiceCatalog';

/**
 *
 * @export
 * @interface SpecialServiceCatalogs
 */
export interface SpecialServiceCatalogs {
  /**
   *
   * @type {Array<SpecialServiceCatalog>}
   * @memberof SpecialServiceCatalogs
   */
  catalogs?: Array<SpecialServiceCatalog>;
}

/**
 * Check if a given object implements the SpecialServiceCatalogs interface.
 */
export function instanceOfSpecialServiceCatalogs(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SpecialServiceCatalogsFromJSON(json: any): SpecialServiceCatalogs {
  return SpecialServiceCatalogsFromJSONTyped(json, false);
}

export function SpecialServiceCatalogsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpecialServiceCatalogs {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    catalogs: !exists(json, 'catalogs')
      ? undefined
      : (json['catalogs'] as Array<any>).map(SpecialServiceCatalogFromJSON),
  };
}

export function SpecialServiceCatalogsToJSON(value?: SpecialServiceCatalogs | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    catalogs:
      value.catalogs === undefined
        ? undefined
        : (value.catalogs as Array<any>).map(SpecialServiceCatalogToJSON),
  };
}
