/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SpecialOrder } from './SpecialOrder';
import {
  SpecialOrderFromJSON,
  SpecialOrderFromJSONTyped,
  SpecialOrderToJSON,
} from './SpecialOrder';

/**
 *
 * @export
 * @interface SpecialOrders
 */
export interface SpecialOrders {
  /**
   *
   * @type {Array<SpecialOrder>}
   * @memberof SpecialOrders
   */
  orders?: Array<SpecialOrder>;
  /**
   *
   * @type {number}
   * @memberof SpecialOrders
   */
  total?: number;
}

/**
 * Check if a given object implements the SpecialOrders interface.
 */
export function instanceOfSpecialOrders(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SpecialOrdersFromJSON(json: any): SpecialOrders {
  return SpecialOrdersFromJSONTyped(json, false);
}

export function SpecialOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecialOrders {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orders: !exists(json, 'orders')
      ? undefined
      : (json['orders'] as Array<any>).map(SpecialOrderFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function SpecialOrdersToJSON(value?: SpecialOrders | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orders:
      value.orders === undefined ? undefined : (value.orders as Array<any>).map(SpecialOrderToJSON),
    total: value.total,
  };
}
