/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SpecialServiceStatus = {
  Draft: 'draft',
  Published: 'published',
} as const;
export type SpecialServiceStatus = (typeof SpecialServiceStatus)[keyof typeof SpecialServiceStatus];

export function SpecialServiceStatusFromJSON(json: any): SpecialServiceStatus {
  return SpecialServiceStatusFromJSONTyped(json, false);
}

export function SpecialServiceStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpecialServiceStatus {
  return json as SpecialServiceStatus;
}

export function SpecialServiceStatusToJSON(value?: SpecialServiceStatus | null): any {
  return value as any;
}
