/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Story } from './Story';
import { StoryFromJSON, StoryFromJSONTyped, StoryToJSON } from './Story';

/**
 *
 * @export
 * @interface StoryServiceUpdateBody
 */
export interface StoryServiceUpdateBody {
  /**
   *
   * @type {Story}
   * @memberof StoryServiceUpdateBody
   */
  story?: Story;
}

/**
 * Check if a given object implements the StoryServiceUpdateBody interface.
 */
export function instanceOfStoryServiceUpdateBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function StoryServiceUpdateBodyFromJSON(json: any): StoryServiceUpdateBody {
  return StoryServiceUpdateBodyFromJSONTyped(json, false);
}

export function StoryServiceUpdateBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StoryServiceUpdateBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    story: !exists(json, 'story') ? undefined : StoryFromJSON(json['story']),
  };
}

export function StoryServiceUpdateBodyToJSON(value?: StoryServiceUpdateBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    story: StoryToJSON(value.story),
  };
}
