/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Journey } from './Journey';
import { JourneyFromJSON, JourneyFromJSONTyped, JourneyToJSON } from './Journey';

/**
 *
 * @export
 * @interface StoryDetail
 */
export interface StoryDetail {
  /**
   *
   * @type {string}
   * @memberof StoryDetail
   */
  kind?: string;
  /**
   *
   * @type {string}
   * @memberof StoryDetail
   */
  recommendedDay?: string;
  /**
   *
   * @type {string}
   * @memberof StoryDetail
   */
  perPersonFee?: string;
  /**
   *
   * @type {Array<Journey>}
   * @memberof StoryDetail
   */
  journey?: Array<Journey>;
  /**
   *
   * @type {string}
   * @memberof StoryDetail
   */
  subTitle?: string | null;
}

/**
 * Check if a given object implements the StoryDetail interface.
 */
export function instanceOfStoryDetail(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function StoryDetailFromJSON(json: any): StoryDetail {
  return StoryDetailFromJSONTyped(json, false);
}

export function StoryDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryDetail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    kind: !exists(json, 'kind') ? undefined : json['kind'],
    recommendedDay: !exists(json, 'recommendedDay') ? undefined : json['recommendedDay'],
    perPersonFee: !exists(json, 'perPersonFee') ? undefined : json['perPersonFee'],
    journey: !exists(json, 'journey')
      ? undefined
      : (json['journey'] as Array<any>).map(JourneyFromJSON),
    subTitle: !exists(json, 'subTitle') ? undefined : json['subTitle'],
  };
}

export function StoryDetailToJSON(value?: StoryDetail | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    kind: value.kind,
    recommendedDay: value.recommendedDay,
    perPersonFee: value.perPersonFee,
    journey:
      value.journey === undefined ? undefined : (value.journey as Array<any>).map(JourneyToJSON),
    subTitle: value.subTitle,
  };
}
