/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoryOperation } from './StoryOperation';
import {
  StoryOperationFromJSON,
  StoryOperationFromJSONTyped,
  StoryOperationToJSON,
} from './StoryOperation';

/**
 *
 * @export
 * @interface StoryOperations
 */
export interface StoryOperations {
  /**
   *
   * @type {Array<StoryOperation>}
   * @memberof StoryOperations
   */
  operations?: Array<StoryOperation>;
  /**
   *
   * @type {number}
   * @memberof StoryOperations
   */
  total?: number;
}

/**
 * Check if a given object implements the StoryOperations interface.
 */
export function instanceOfStoryOperations(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function StoryOperationsFromJSON(json: any): StoryOperations {
  return StoryOperationsFromJSONTyped(json, false);
}

export function StoryOperationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StoryOperations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    operations: !exists(json, 'operations')
      ? undefined
      : (json['operations'] as Array<any>).map(StoryOperationFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function StoryOperationsToJSON(value?: StoryOperations | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    operations:
      value.operations === undefined
        ? undefined
        : (value.operations as Array<any>).map(StoryOperationToJSON),
    total: value.total,
  };
}
