/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoryStatus } from './StoryStatus';
import { StoryStatusFromJSON, StoryStatusFromJSONTyped, StoryStatusToJSON } from './StoryStatus';

/**
 *
 * @export
 * @interface StoryAdminServiceUpdateStatusBody
 */
export interface StoryAdminServiceUpdateStatusBody {
  /**
   *
   * @type {StoryStatus}
   * @memberof StoryAdminServiceUpdateStatusBody
   */
  status?: StoryStatus;
}

/**
 * Check if a given object implements the StoryAdminServiceUpdateStatusBody interface.
 */
export function instanceOfStoryAdminServiceUpdateStatusBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function StoryAdminServiceUpdateStatusBodyFromJSON(
  json: any,
): StoryAdminServiceUpdateStatusBody {
  return StoryAdminServiceUpdateStatusBodyFromJSONTyped(json, false);
}

export function StoryAdminServiceUpdateStatusBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StoryAdminServiceUpdateStatusBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, 'status') ? undefined : StoryStatusFromJSON(json['status']),
  };
}

export function StoryAdminServiceUpdateStatusBodyToJSON(
  value?: StoryAdminServiceUpdateStatusBody | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: StoryStatusToJSON(value.status),
  };
}
