/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubMessage
 */
export interface SubMessage {
  /**
   *
   * @type {string}
   * @memberof SubMessage
   */
  subfield?: string;
}

/**
 * Check if a given object implements the SubMessage interface.
 */
export function instanceOfSubMessage(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SubMessageFromJSON(json: any): SubMessage {
  return SubMessageFromJSONTyped(json, false);
}

export function SubMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubMessage {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    subfield: !exists(json, 'subfield') ? undefined : json['subfield'],
  };
}

export function SubMessageToJSON(value?: SubMessage | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    subfield: value.subfield,
  };
}
