/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Tag } from './V1Tag';
import { V1TagFromJSON, V1TagFromJSONTyped, V1TagToJSON } from './V1Tag';

/**
 *
 * @export
 * @interface TagCreateReq
 */
export interface TagCreateReq {
  /**
   *
   * @type {V1Tag}
   * @memberof TagCreateReq
   */
  tag?: V1Tag;
}

/**
 * Check if a given object implements the TagCreateReq interface.
 */
export function instanceOfTagCreateReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TagCreateReqFromJSON(json: any): TagCreateReq {
  return TagCreateReqFromJSONTyped(json, false);
}

export function TagCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCreateReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tag: !exists(json, 'Tag') ? undefined : V1TagFromJSON(json['Tag']),
  };
}

export function TagCreateReqToJSON(value?: TagCreateReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Tag: V1TagToJSON(value.tag),
  };
}
