/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TagKind = {
  Attr: 'attr',
  Func: 'func',
  Desc: 'desc',
} as const;
export type TagKind = (typeof TagKind)[keyof typeof TagKind];

export function TagKindFromJSON(json: any): TagKind {
  return TagKindFromJSONTyped(json, false);
}

export function TagKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagKind {
  return json as TagKind;
}

export function TagKindToJSON(value?: TagKind | null): any {
  return value as any;
}
