/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Task } from './Task';
import { TaskFromJSON, TaskFromJSONTyped, TaskToJSON } from './Task';

/**
 *
 * @export
 * @interface Tasks
 */
export interface Tasks {
  /**
   *
   * @type {Array<Task>}
   * @memberof Tasks
   */
  data?: Array<Task>;
  /**
   *
   * @type {number}
   * @memberof Tasks
   */
  total?: number;
}

/**
 * Check if a given object implements the Tasks interface.
 */
export function instanceOfTasks(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TasksFromJSON(json: any): Tasks {
  return TasksFromJSONTyped(json, false);
}

export function TasksFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tasks {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(TaskFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function TasksToJSON(value?: Tasks | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(TaskToJSON),
    total: value.total,
  };
}
