/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualGoodOrderStatus } from './VirtualGoodOrderStatus';
import {
  VirtualGoodOrderStatusFromJSON,
  VirtualGoodOrderStatusFromJSONTyped,
  VirtualGoodOrderStatusToJSON,
} from './VirtualGoodOrderStatus';

/**
 *
 * @export
 * @interface UpdateOrderStatusBody
 */
export interface UpdateOrderStatusBody {
  /**
   *
   * @type {VirtualGoodOrderStatus}
   * @memberof UpdateOrderStatusBody
   */
  status?: VirtualGoodOrderStatus;
}

/**
 * Check if a given object implements the UpdateOrderStatusBody interface.
 */
export function instanceOfUpdateOrderStatusBody(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateOrderStatusBodyFromJSON(json: any): UpdateOrderStatusBody {
  return UpdateOrderStatusBodyFromJSONTyped(json, false);
}

export function UpdateOrderStatusBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOrderStatusBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, 'status') ? undefined : VirtualGoodOrderStatusFromJSON(json['status']),
  };
}

export function UpdateOrderStatusBodyToJSON(value?: UpdateOrderStatusBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: VirtualGoodOrderStatusToJSON(value.status),
  };
}
