/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from './User';

/**
 *
 * @export
 * @interface UserServiceUpdateBody
 */
export interface UserServiceUpdateBody {
  /**
   *
   * @type {User}
   * @memberof UserServiceUpdateBody
   */
  user: User;
}

/**
 * Check if a given object implements the UserServiceUpdateBody interface.
 */
export function instanceOfUserServiceUpdateBody(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;

  return isInstance;
}

export function UserServiceUpdateBodyFromJSON(json: any): UserServiceUpdateBody {
  return UserServiceUpdateBodyFromJSONTyped(json, false);
}

export function UserServiceUpdateBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserServiceUpdateBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserFromJSON(json['user']),
  };
}

export function UserServiceUpdateBodyToJSON(value?: UserServiceUpdateBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserToJSON(value.user),
  };
}
