/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  avatar?: string;
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  nickname?: string;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'email' in value;

  return isInstance;
}

export function UserInfoFromJSON(json: any): UserInfo {
  return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    avatar: !exists(json, 'avatar') ? undefined : json['avatar'],
    nickname: !exists(json, 'nickname') ? undefined : json['nickname'],
  };
}

export function UserInfoToJSON(value?: UserInfo | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    email: value.email,
    avatar: value.avatar,
    nickname: value.nickname,
  };
}
