/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserGetNonceRsp
 */
export interface UserGetNonceRsp {
  /**
   *
   * @type {string}
   * @memberof UserGetNonceRsp
   */
  nonce?: string;
}

/**
 * Check if a given object implements the UserGetNonceRsp interface.
 */
export function instanceOfUserGetNonceRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserGetNonceRspFromJSON(json: any): UserGetNonceRsp {
  return UserGetNonceRspFromJSONTyped(json, false);
}

export function UserGetNonceRspFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserGetNonceRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    nonce: !exists(json, 'nonce') ? undefined : json['nonce'],
  };
}

export function UserGetNonceRspToJSON(value?: UserGetNonceRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    nonce: value.nonce,
  };
}
