/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserUpdateAvatarRsp
 */
export interface UserUpdateAvatarRsp {
  /**
   *
   * @type {string}
   * @memberof UserUpdateAvatarRsp
   */
  avatar?: string;
}

/**
 * Check if a given object implements the UserUpdateAvatarRsp interface.
 */
export function instanceOfUserUpdateAvatarRsp(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserUpdateAvatarRspFromJSON(json: any): UserUpdateAvatarRsp {
  return UserUpdateAvatarRspFromJSONTyped(json, false);
}

export function UserUpdateAvatarRspFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserUpdateAvatarRsp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    avatar: !exists(json, 'avatar') ? undefined : json['avatar'],
  };
}

export function UserUpdateAvatarRspToJSON(value?: UserUpdateAvatarRsp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    avatar: value.avatar,
  };
}
