/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualGood } from './VirtualGood';
import { VirtualGoodFromJSON, VirtualGoodFromJSONTyped, VirtualGoodToJSON } from './VirtualGood';

/**
 *
 * @export
 * @interface VirtualGoodRaffle
 */
export interface VirtualGoodRaffle {
  /**
   *
   * @type {Date}
   * @memberof VirtualGoodRaffle
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof VirtualGoodRaffle
   */
  updatedAt?: Date;
  /**
   *
   * @type {number}
   * @memberof VirtualGoodRaffle
   */
  points?: number;
  /**
   *
   * @type {Array<VirtualGood>}
   * @memberof VirtualGoodRaffle
   */
  goods?: Array<VirtualGood>;
  /**
   *
   * @type {string}
   * @memberof VirtualGoodRaffle
   */
  description?: string | null;
}

/**
 * Check if a given object implements the VirtualGoodRaffle interface.
 */
export function instanceOfVirtualGoodRaffle(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VirtualGoodRaffleFromJSON(json: any): VirtualGoodRaffle {
  return VirtualGoodRaffleFromJSONTyped(json, false);
}

export function VirtualGoodRaffleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VirtualGoodRaffle {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    points: !exists(json, 'points') ? undefined : json['points'],
    goods: !exists(json, 'goods')
      ? undefined
      : (json['goods'] as Array<any>).map(VirtualGoodFromJSON),
    description: !exists(json, 'description') ? undefined : json['description'],
  };
}

export function VirtualGoodRaffleToJSON(value?: VirtualGoodRaffle | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    points: value.points,
    goods:
      value.goods === undefined ? undefined : (value.goods as Array<any>).map(VirtualGoodToJSON),
    description: value.description,
  };
}
