/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualGood } from './VirtualGood';
import { VirtualGoodFromJSON, VirtualGoodFromJSONTyped, VirtualGoodToJSON } from './VirtualGood';

/**
 *
 * @export
 * @interface VirtualGoodOrderDetail
 */
export interface VirtualGoodOrderDetail {
  /**
   *
   * @type {VirtualGood}
   * @memberof VirtualGoodOrderDetail
   */
  good?: VirtualGood;
  /**
   *
   * @type {string}
   * @memberof VirtualGoodOrderDetail
   */
  logisticsCompany?: string | null;
  /**
   *
   * @type {string}
   * @memberof VirtualGoodOrderDetail
   */
  logisticsNumber?: string | null;
}

/**
 * Check if a given object implements the VirtualGoodOrderDetail interface.
 */
export function instanceOfVirtualGoodOrderDetail(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VirtualGoodOrderDetailFromJSON(json: any): VirtualGoodOrderDetail {
  return VirtualGoodOrderDetailFromJSONTyped(json, false);
}

export function VirtualGoodOrderDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VirtualGoodOrderDetail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    good: !exists(json, 'good') ? undefined : VirtualGoodFromJSON(json['good']),
    logisticsCompany: !exists(json, 'logisticsCompany') ? undefined : json['logisticsCompany'],
    logisticsNumber: !exists(json, 'logisticsNumber') ? undefined : json['logisticsNumber'],
  };
}

export function VirtualGoodOrderDetailToJSON(value?: VirtualGoodOrderDetail | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    good: VirtualGoodToJSON(value.good),
    logisticsCompany: value.logisticsCompany,
    logisticsNumber: value.logisticsNumber,
  };
}
