/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * - physical: 实体
 *  - virtual: 虚拟
 *  - empty: 空类型
 * @export
 */
export const VirtualGoodType = {
  Physical: 'physical',
  Virtual: 'virtual',
  Empty: 'empty',
} as const;
export type VirtualGoodType = (typeof VirtualGoodType)[keyof typeof VirtualGoodType];

export function VirtualGoodTypeFromJSON(json: any): VirtualGoodType {
  return VirtualGoodTypeFromJSONTyped(json, false);
}

export function VirtualGoodTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VirtualGoodType {
  return json as VirtualGoodType;
}

export function VirtualGoodTypeToJSON(value?: VirtualGoodType | null): any {
  return value as any;
}
