/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualGoodRaffleRecord } from './VirtualGoodRaffleRecord';
import {
  VirtualGoodRaffleRecordFromJSON,
  VirtualGoodRaffleRecordFromJSONTyped,
  VirtualGoodRaffleRecordToJSON,
} from './VirtualGoodRaffleRecord';

/**
 *
 * @export
 * @interface VirtualGoodRaffleRecords
 */
export interface VirtualGoodRaffleRecords {
  /**
   *
   * @type {Array<VirtualGoodRaffleRecord>}
   * @memberof VirtualGoodRaffleRecords
   */
  data?: Array<VirtualGoodRaffleRecord>;
  /**
   *
   * @type {number}
   * @memberof VirtualGoodRaffleRecords
   */
  total?: number;
}

/**
 * Check if a given object implements the VirtualGoodRaffleRecords interface.
 */
export function instanceOfVirtualGoodRaffleRecords(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VirtualGoodRaffleRecordsFromJSON(json: any): VirtualGoodRaffleRecords {
  return VirtualGoodRaffleRecordsFromJSONTyped(json, false);
}

export function VirtualGoodRaffleRecordsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VirtualGoodRaffleRecords {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(VirtualGoodRaffleRecordFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function VirtualGoodRaffleRecordsToJSON(value?: VirtualGoodRaffleRecords | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(VirtualGoodRaffleRecordToJSON),
    total: value.total,
  };
}
