/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Language } from './Language';
import { LanguageFromJSON, LanguageFromJSONTyped, LanguageToJSON } from './Language';
import type { VirtualGoodDetail } from './VirtualGoodDetail';
import {
  VirtualGoodDetailFromJSON,
  VirtualGoodDetailFromJSONTyped,
  VirtualGoodDetailToJSON,
} from './VirtualGoodDetail';
import type { VirtualGoodKind } from './VirtualGoodKind';
import {
  VirtualGoodKindFromJSON,
  VirtualGoodKindFromJSONTyped,
  VirtualGoodKindToJSON,
} from './VirtualGoodKind';
import type { VirtualGoodStatus } from './VirtualGoodStatus';
import {
  VirtualGoodStatusFromJSON,
  VirtualGoodStatusFromJSONTyped,
  VirtualGoodStatusToJSON,
} from './VirtualGoodStatus';
import type { VirtualGoodType } from './VirtualGoodType';
import {
  VirtualGoodTypeFromJSON,
  VirtualGoodTypeFromJSONTyped,
  VirtualGoodTypeToJSON,
} from './VirtualGoodType';

/**
 *
 * @export
 * @interface VirtualGood
 */
export interface VirtualGood {
  /**
   *
   * @type {string}
   * @memberof VirtualGood
   */
  id?: string | null;
  /**
   *
   * @type {Date}
   * @memberof VirtualGood
   */
  readonly createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof VirtualGood
   */
  readonly updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof VirtualGood
   */
  name?: string;
  /**
   *
   * @type {Language}
   * @memberof VirtualGood
   */
  language?: Language;
  /**
   *
   * @type {string}
   * @memberof VirtualGood
   */
  thumbnail?: string | null;
  /**
   *
   * @type {VirtualGoodKind}
   * @memberof VirtualGood
   */
  kind?: VirtualGoodKind;
  /**
   *
   * @type {number}
   * @memberof VirtualGood
   */
  points?: number | null;
  /**
   *
   * @type {Array<string>}
   * @memberof VirtualGood
   */
  images?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof VirtualGood
   */
  description?: string | null;
  /**
   *
   * @type {VirtualGoodDetail}
   * @memberof VirtualGood
   */
  detail?: VirtualGoodDetail;
  /**
   *
   * @type {VirtualGoodStatus}
   * @memberof VirtualGood
   */
  status: VirtualGoodStatus;
  /**
   *
   * @type {VirtualGoodType}
   * @memberof VirtualGood
   */
  type?: VirtualGoodType;
  /**
   *
   * @type {number}
   * @memberof VirtualGood
   */
  skuCount?: number | null;
}

/**
 * Check if a given object implements the VirtualGood interface.
 */
export function instanceOfVirtualGood(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'createdAt' in value;
  isInstance = isInstance && 'updatedAt' in value;
  isInstance = isInstance && 'status' in value;

  return isInstance;
}

export function VirtualGoodFromJSON(json: any): VirtualGood {
  return VirtualGoodFromJSONTyped(json, false);
}

export function VirtualGoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualGood {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    name: !exists(json, 'name') ? undefined : json['name'],
    language: !exists(json, 'language') ? undefined : LanguageFromJSON(json['language']),
    thumbnail: !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
    kind: !exists(json, 'kind') ? undefined : VirtualGoodKindFromJSON(json['kind']),
    points: !exists(json, 'points') ? undefined : json['points'],
    images: !exists(json, 'images') ? undefined : json['images'],
    description: !exists(json, 'description') ? undefined : json['description'],
    detail: !exists(json, 'detail') ? undefined : VirtualGoodDetailFromJSON(json['detail']),
    status: VirtualGoodStatusFromJSON(json['status']),
    type: !exists(json, 'type') ? undefined : VirtualGoodTypeFromJSON(json['type']),
    skuCount: !exists(json, 'skuCount') ? undefined : json['skuCount'],
  };
}

export function VirtualGoodToJSON(value?: VirtualGood | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    language: LanguageToJSON(value.language),
    thumbnail: value.thumbnail,
    kind: VirtualGoodKindToJSON(value.kind),
    points: value.points,
    images: value.images,
    description: value.description,
    detail: VirtualGoodDetailToJSON(value.detail),
    status: VirtualGoodStatusToJSON(value.status),
    type: VirtualGoodTypeToJSON(value.type),
    skuCount: value.skuCount,
  };
}
