/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualGood } from './VirtualGood';
import { VirtualGoodFromJSON, VirtualGoodFromJSONTyped, VirtualGoodToJSON } from './VirtualGood';

/**
 *
 * @export
 * @interface VirtualGoodRaffleRecordDetail
 */
export interface VirtualGoodRaffleRecordDetail {
  /**
   *
   * @type {VirtualGood}
   * @memberof VirtualGoodRaffleRecordDetail
   */
  virtualGood?: VirtualGood;
}

/**
 * Check if a given object implements the VirtualGoodRaffleRecordDetail interface.
 */
export function instanceOfVirtualGoodRaffleRecordDetail(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VirtualGoodRaffleRecordDetailFromJSON(json: any): VirtualGoodRaffleRecordDetail {
  return VirtualGoodRaffleRecordDetailFromJSONTyped(json, false);
}

export function VirtualGoodRaffleRecordDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VirtualGoodRaffleRecordDetail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    virtualGood: !exists(json, 'virtualGood')
      ? undefined
      : VirtualGoodFromJSON(json['virtualGood']),
  };
}

export function VirtualGoodRaffleRecordDetailToJSON(
  value?: VirtualGoodRaffleRecordDetail | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    virtualGood: VirtualGoodToJSON(value.virtualGood),
  };
}
