/* tslint:disable */
/* eslint-disable */
/**
 * chameleon service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: none@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReportLocationReq } from './ReportLocationReq';
import {
  ReportLocationReqFromJSON,
  ReportLocationReqFromJSONTyped,
  ReportLocationReqToJSON,
} from './ReportLocationReq';

/**
 *
 * @export
 * @interface WebsocketCreateReq
 */
export interface WebsocketCreateReq {
  /**
   *
   * @type {ReportLocationReq}
   * @memberof WebsocketCreateReq
   */
  location?: ReportLocationReq;
  /**
   *
   * @type {string}
   * @memberof WebsocketCreateReq
   */
  echo?: string;
}

/**
 * Check if a given object implements the WebsocketCreateReq interface.
 */
export function instanceOfWebsocketCreateReq(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function WebsocketCreateReqFromJSON(json: any): WebsocketCreateReq {
  return WebsocketCreateReqFromJSONTyped(json, false);
}

export function WebsocketCreateReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebsocketCreateReq {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    location: !exists(json, 'location') ? undefined : ReportLocationReqFromJSON(json['location']),
    echo: !exists(json, 'echo') ? undefined : json['echo'],
  };
}

export function WebsocketCreateReqToJSON(value?: WebsocketCreateReq | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    location: ReportLocationReqToJSON(value.location),
    echo: value.echo,
  };
}
